// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api_walker.proto

#include "api_walker.pb.h"
#include "api_walker.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace apiwalker {

static const char* ApiWalker_method_names[] = {
  "/apiwalker.ApiWalker/GetReply",
};

std::unique_ptr< ApiWalker::Stub> ApiWalker::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ApiWalker::Stub> stub(new ApiWalker::Stub(channel, options));
  return stub;
}

ApiWalker::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetReply_(ApiWalker_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ApiWalker::Stub::GetReply(::grpc::ClientContext* context, const ::apiwalker::RequestMessage& request, ::apiwalker::ReplyMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::apiwalker::RequestMessage, ::apiwalker::ReplyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetReply_, context, request, response);
}

void ApiWalker::Stub::async::GetReply(::grpc::ClientContext* context, const ::apiwalker::RequestMessage* request, ::apiwalker::ReplyMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::apiwalker::RequestMessage, ::apiwalker::ReplyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetReply_, context, request, response, std::move(f));
}

void ApiWalker::Stub::async::GetReply(::grpc::ClientContext* context, const ::apiwalker::RequestMessage* request, ::apiwalker::ReplyMessage* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetReply_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::apiwalker::ReplyMessage>* ApiWalker::Stub::PrepareAsyncGetReplyRaw(::grpc::ClientContext* context, const ::apiwalker::RequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::apiwalker::ReplyMessage, ::apiwalker::RequestMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetReply_, context, request);
}

::grpc::ClientAsyncResponseReader< ::apiwalker::ReplyMessage>* ApiWalker::Stub::AsyncGetReplyRaw(::grpc::ClientContext* context, const ::apiwalker::RequestMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetReplyRaw(context, request, cq);
  result->StartCall();
  return result;
}

ApiWalker::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ApiWalker_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ApiWalker::Service, ::apiwalker::RequestMessage, ::apiwalker::ReplyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ApiWalker::Service* service,
             ::grpc::ServerContext* ctx,
             const ::apiwalker::RequestMessage* req,
             ::apiwalker::ReplyMessage* resp) {
               return service->GetReply(ctx, req, resp);
             }, this)));
}

ApiWalker::Service::~Service() {
}

::grpc::Status ApiWalker::Service::GetReply(::grpc::ServerContext* context, const ::apiwalker::RequestMessage* request, ::apiwalker::ReplyMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace apiwalker

