// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api_walker.proto
#ifndef GRPC_api_5fwalker_2eproto__INCLUDED
#define GRPC_api_5fwalker_2eproto__INCLUDED

#include "api_walker.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace apiwalker {

class ApiWalker final {
 public:
  static constexpr char const* service_full_name() {
    return "apiwalker.ApiWalker";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetReply(::grpc::ClientContext* context, const ::apiwalker::RequestMessage& request, ::apiwalker::ReplyMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::apiwalker::ReplyMessage>> AsyncGetReply(::grpc::ClientContext* context, const ::apiwalker::RequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::apiwalker::ReplyMessage>>(AsyncGetReplyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::apiwalker::ReplyMessage>> PrepareAsyncGetReply(::grpc::ClientContext* context, const ::apiwalker::RequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::apiwalker::ReplyMessage>>(PrepareAsyncGetReplyRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetReply(::grpc::ClientContext* context, const ::apiwalker::RequestMessage* request, ::apiwalker::ReplyMessage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetReply(::grpc::ClientContext* context, const ::apiwalker::RequestMessage* request, ::apiwalker::ReplyMessage* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::apiwalker::ReplyMessage>* AsyncGetReplyRaw(::grpc::ClientContext* context, const ::apiwalker::RequestMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::apiwalker::ReplyMessage>* PrepareAsyncGetReplyRaw(::grpc::ClientContext* context, const ::apiwalker::RequestMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetReply(::grpc::ClientContext* context, const ::apiwalker::RequestMessage& request, ::apiwalker::ReplyMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::apiwalker::ReplyMessage>> AsyncGetReply(::grpc::ClientContext* context, const ::apiwalker::RequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::apiwalker::ReplyMessage>>(AsyncGetReplyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::apiwalker::ReplyMessage>> PrepareAsyncGetReply(::grpc::ClientContext* context, const ::apiwalker::RequestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::apiwalker::ReplyMessage>>(PrepareAsyncGetReplyRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetReply(::grpc::ClientContext* context, const ::apiwalker::RequestMessage* request, ::apiwalker::ReplyMessage* response, std::function<void(::grpc::Status)>) override;
      void GetReply(::grpc::ClientContext* context, const ::apiwalker::RequestMessage* request, ::apiwalker::ReplyMessage* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::apiwalker::ReplyMessage>* AsyncGetReplyRaw(::grpc::ClientContext* context, const ::apiwalker::RequestMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::apiwalker::ReplyMessage>* PrepareAsyncGetReplyRaw(::grpc::ClientContext* context, const ::apiwalker::RequestMessage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetReply_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetReply(::grpc::ServerContext* context, const ::apiwalker::RequestMessage* request, ::apiwalker::ReplyMessage* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetReply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetReply() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetReply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReply(::grpc::ServerContext* /*context*/, const ::apiwalker::RequestMessage* /*request*/, ::apiwalker::ReplyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetReply(::grpc::ServerContext* context, ::apiwalker::RequestMessage* request, ::grpc::ServerAsyncResponseWriter< ::apiwalker::ReplyMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetReply<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetReply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetReply() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::apiwalker::RequestMessage, ::apiwalker::ReplyMessage>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::apiwalker::RequestMessage* request, ::apiwalker::ReplyMessage* response) { return this->GetReply(context, request, response); }));}
    void SetMessageAllocatorFor_GetReply(
        ::grpc::MessageAllocator< ::apiwalker::RequestMessage, ::apiwalker::ReplyMessage>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::apiwalker::RequestMessage, ::apiwalker::ReplyMessage>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetReply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReply(::grpc::ServerContext* /*context*/, const ::apiwalker::RequestMessage* /*request*/, ::apiwalker::ReplyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetReply(
      ::grpc::CallbackServerContext* /*context*/, const ::apiwalker::RequestMessage* /*request*/, ::apiwalker::ReplyMessage* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetReply<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetReply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetReply() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetReply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReply(::grpc::ServerContext* /*context*/, const ::apiwalker::RequestMessage* /*request*/, ::apiwalker::ReplyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetReply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetReply() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetReply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReply(::grpc::ServerContext* /*context*/, const ::apiwalker::RequestMessage* /*request*/, ::apiwalker::ReplyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetReply(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetReply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetReply() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetReply(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetReply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReply(::grpc::ServerContext* /*context*/, const ::apiwalker::RequestMessage* /*request*/, ::apiwalker::ReplyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetReply(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetReply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetReply() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::apiwalker::RequestMessage, ::apiwalker::ReplyMessage>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::apiwalker::RequestMessage, ::apiwalker::ReplyMessage>* streamer) {
                       return this->StreamedGetReply(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetReply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetReply(::grpc::ServerContext* /*context*/, const ::apiwalker::RequestMessage* /*request*/, ::apiwalker::ReplyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetReply(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::apiwalker::RequestMessage,::apiwalker::ReplyMessage>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetReply<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetReply<Service > StreamedService;
};

}  // namespace apiwalker


#endif  // GRPC_api_5fwalker_2eproto__INCLUDED
